version: "3.8"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: kenton
      POSTGRES_PASSWORD: duprey
      POSTGRES_DB: kenton_duprey
    ports:
      - "5438:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
