name: Cut Patch Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions: write-all

# when a push is made to develop branch by dependabot or github-actions, or the merge branch includes 'hotfix', it will cut a patch release

jobs:
  cutPatchRelease:
    if: github.actor == 'dependabot[bot]' || github.actor == 'github-actions' || contains(github.event.pull_request.head.ref, 'hotfix') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Cut Patch Release
    outputs:
      v_patch: ${{ steps.semvers.outputs.v_patch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get next version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1.2.1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semvers.outputs.v_patch }}
          generateReleaseNotes: true
          commit: "main"

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ steps.semvers.outputs.v_patch }}
          ignore_missing: true
