name: Cut Minor Release

on:
  push:
    branches:
      - main

# when a push is made to develop branch by kduprey, and the merge branch does not include hotfix, it will cut a minor release

jobs:
  cutMinorRelease:
    if: github.actor == 'kduprey' && !contains(github.event.head_commit.message, 'hotfix')
    runs-on: ubuntu-latest
    name: Cut Minor Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          prefix: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1.2.1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semvers.outputs.v_minor }}
          generateReleaseNotes: true
          commit: "main"

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ steps.semvers.outputs.v_minor }}
